[package]
name = "aoc01b"
version = "0.1.0"
authors = ["Andrew Huang <andrew.huang@softwire.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
